// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/ice/Desktop/x/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.27.4_@swc+helpers@0.5.1_@types+node@24.0.3_@types+react@19.1.8_esli_3yxjug2ps2pmret6lhtzh77saa/node_modules/dumi/theme-default/slots/ContentFooter/index.js';
