// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/ice/Desktop/x/node_modules/.pnpm/dumi-plugin-color-chunk@1.1.2_@babel+core@7.27.4_@swc+helpers@0.5.1_@types+node@24.0.3_@types_w7ynpsheoyryb7vvau2axain24/node_modules/dumi-plugin-color-chunk/es/component/index.js';
